version: "3.7"
services:
  django_app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: django_app
    volumes:
      - ./mysite:/app/mysite
    ports:
      - '8000:8000'
    depends_on:
      - psql_db

  psql_db:
    image: postgres:16.2-alpine3.19
    container_name: psql_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery-beat:
    build: .
    command: celery -A mysite beat -l info
    volumes:
      - ./mysite:/app/mysite
    depends_on:
      - redis

  celery-worker:
    build: .
    command: celery -A mysite worker -l info
    volumes:
      - ./mysite:/app/mysite
    depends_on:
      - redis

volumes:
  postgres_data:
