# Generated by Django 5.0.6 on 2024-05-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='pub_date',
        ),
    ]
