# Generated by Django 4.2.14 on 2024-07-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_message_author_alter_message_replied_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.message'),
        ),
    ]
